import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.flink.java-conventions")
    id("com.github.johnrengelman.shadow") version "7.1.0"
}

dependencies {
    api(project(":flink-test-utils-junit"))
    implementation(project(":flink-core"))
    implementation(project(":flink-runtime"))
    implementation(project(":flink-runtime", "testArtifacts"))
    implementation(project(":flink-rpc-akka-loader"))
    implementation(project(":flink-clients"))
    implementation(project(":flink-streaming-java"))
    implementation("org.apache.commons:commons-lang3:3.3.2")
    implementation("io.netty:netty:3.10.6.Final")
    implementation("org.apache.curator:curator-test:2.12.0")
    implementation("org.apache.hadoop:hadoop-minikdc:3.2.0")
    implementation("org.apache.flink:flink-shaded-netty:4.1.65.Final-14.0")
    runtimeOnly(project(":flink-statebackend-changelog"))
}

description = "Flink : Test utils : Utils"

tasks.withType<ShadowJar> {
    dependencies {
        include(dependency("io.netty:netty"))
    }

    relocate("org.jboss.netty", "org.apache.flink.shaded.testutils.org.jboss.netty")
    exclude("META-INF/maven/io.netty/**")
}
